apiVersion: skaffold/v4beta11
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: nejmimouhsine1/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: nejmimouhsine1/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.tsx'
            dest: .
    - image: nejmimouhsine1/group
      context: group
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.tsx'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*
